// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef PHIEU_NHAP_KHO_ODB_HXX
#define PHIEU_NHAP_KHO_ODB_HXX

// Begin prologue.
//
#include <odb/qt/version.hxx>
#if ODB_QT_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-qt interface versions
#endif
#include <odb/qt/basic/oracle/qstring-traits.hxx>
#include <odb/qt/basic/oracle/qbyte-array-traits.hxx>
#include <odb/qt/basic/oracle/quuid-traits.hxx>
#include <odb/qt/containers/qhash-traits.hxx>
#include <odb/qt/containers/qlist-traits.hxx>
#include <odb/qt/containers/qlinked-list-traits.hxx>
#include <odb/qt/containers/qmap-traits.hxx>
#include <odb/qt/containers/qset-traits.hxx>
#include <odb/qt/containers/qvector-traits.hxx>
#include <odb/qt/date-time/oracle/qdate-traits.hxx>
#include <odb/qt/date-time/oracle/qtime-traits.hxx>
#include <odb/qt/date-time/oracle/qdate-time-traits.hxx>
#include <QtCore/QSharedPointer>
#include <odb/qt/smart-ptr/pointer-traits.hxx>
#include <odb/qt/smart-ptr/wrapper-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "PhieuNhapKho.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // PhieuNhapKho
  //
  template <>
  struct class_traits< ::PhieuNhapKho >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::PhieuNhapKho >
  {
    public:
    typedef ::PhieuNhapKho object_type;
    typedef ::std::shared_ptr< ::PhieuNhapKho > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::size_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/oracle/version.hxx>
#include <odb/oracle/forward.hxx>
#include <odb/oracle/binding.hxx>
#include <odb/oracle/oracle-types.hxx>
#include <odb/oracle/query.hxx>

namespace odb
{
  // PhieuNhapKho
  //
  template <typename A>
  struct query_columns< ::PhieuNhapKho, id_oracle, A >
  {
    // mPhieuNhapKhoId
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::size_t,
        oracle::id_big_int >::query_type,
      oracle::id_big_int >
    mPhieuNhapKhoId_type_;

    static const mPhieuNhapKhoId_type_ mPhieuNhapKhoId;

    // mKhoId
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::size_t,
        oracle::id_big_int >::query_type,
      oracle::id_big_int >
    mKhoId_type_;

    static const mKhoId_type_ mKhoId;

    // mDanhMucCoQuanTypeId
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::size_t,
        oracle::id_big_int >::query_type,
      oracle::id_big_int >
    mDanhMucCoQuanTypeId_type_;

    static const mDanhMucCoQuanTypeId_type_ mDanhMucCoQuanTypeId;

    // mSoPhieu
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::QString,
        oracle::id_nstring >::query_type,
      oracle::id_nstring >
    mSoPhieu_type_;

    static const mSoPhieu_type_ mSoPhieu;

    // mTenNguoiGiao
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::QString,
        oracle::id_nstring >::query_type,
      oracle::id_nstring >
    mTenNguoiGiao_type_;

    static const mTenNguoiGiao_type_ mTenNguoiGiao;

    // mNgayNhapKho
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::QDate,
        oracle::id_date >::query_type,
      oracle::id_date >
    mNgayNhapKho_type_;

    static const mNgayNhapKho_type_ mNgayNhapKho;

    // mGhiChu
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::QString,
        oracle::id_nstring >::query_type,
      oracle::id_nstring >
    mGhiChu_type_;

    static const mGhiChu_type_ mGhiChu;

    // mNguoiSuaId
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::size_t,
        oracle::id_big_int >::query_type,
      oracle::id_big_int >
    mNguoiSuaId_type_;

    static const mNguoiSuaId_type_ mNguoiSuaId;

    // mNgayChinhSua
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::QDate,
        oracle::id_date >::query_type,
      oracle::id_date >
    mNgayChinhSua_type_;

    static const mNgayChinhSua_type_ mNgayChinhSua;

    // mTrangThai
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        bool,
        oracle::id_int32 >::query_type,
      oracle::id_int32 >
    mTrangThai_type_;

    static const mTrangThai_type_ mTrangThai;
  };

  template <typename A>
  const typename query_columns< ::PhieuNhapKho, id_oracle, A >::mPhieuNhapKhoId_type_
  query_columns< ::PhieuNhapKho, id_oracle, A >::
  mPhieuNhapKhoId (A::table_name, "\"PHIEUNHAPKHOID\"", 0, 20);

  template <typename A>
  const typename query_columns< ::PhieuNhapKho, id_oracle, A >::mKhoId_type_
  query_columns< ::PhieuNhapKho, id_oracle, A >::
  mKhoId (A::table_name, "\"KHOID\"", 0, 20);

  template <typename A>
  const typename query_columns< ::PhieuNhapKho, id_oracle, A >::mDanhMucCoQuanTypeId_type_
  query_columns< ::PhieuNhapKho, id_oracle, A >::
  mDanhMucCoQuanTypeId (A::table_name, "\"DANHMUCCOQUANTYPEID\"", 0, 20);

  template <typename A>
  const typename query_columns< ::PhieuNhapKho, id_oracle, A >::mSoPhieu_type_
  query_columns< ::PhieuNhapKho, id_oracle, A >::
  mSoPhieu (A::table_name, "\"SOPHIEU\"", 0, 200);

  template <typename A>
  const typename query_columns< ::PhieuNhapKho, id_oracle, A >::mTenNguoiGiao_type_
  query_columns< ::PhieuNhapKho, id_oracle, A >::
  mTenNguoiGiao (A::table_name, "\"TENNGUOIGIAO\"", 0, 200);

  template <typename A>
  const typename query_columns< ::PhieuNhapKho, id_oracle, A >::mNgayNhapKho_type_
  query_columns< ::PhieuNhapKho, id_oracle, A >::
  mNgayNhapKho (A::table_name, "\"NGAYNHAPKHO\"", 0);

  template <typename A>
  const typename query_columns< ::PhieuNhapKho, id_oracle, A >::mGhiChu_type_
  query_columns< ::PhieuNhapKho, id_oracle, A >::
  mGhiChu (A::table_name, "\"GHICHU\"", 0, 1020);

  template <typename A>
  const typename query_columns< ::PhieuNhapKho, id_oracle, A >::mNguoiSuaId_type_
  query_columns< ::PhieuNhapKho, id_oracle, A >::
  mNguoiSuaId (A::table_name, "\"NGUOISUAID\"", 0, 20);

  template <typename A>
  const typename query_columns< ::PhieuNhapKho, id_oracle, A >::mNgayChinhSua_type_
  query_columns< ::PhieuNhapKho, id_oracle, A >::
  mNgayChinhSua (A::table_name, "\"NGAYCHINHSUA\"", 0);

  template <typename A>
  const typename query_columns< ::PhieuNhapKho, id_oracle, A >::mTrangThai_type_
  query_columns< ::PhieuNhapKho, id_oracle, A >::
  mTrangThai (A::table_name, "\"TRANGTHAI\"", 0, 1);

  template <typename A>
  struct pointer_query_columns< ::PhieuNhapKho, id_oracle, A >:
    query_columns< ::PhieuNhapKho, id_oracle, A >
  {
  };

  template <>
  class access::object_traits_impl< ::PhieuNhapKho, id_oracle >:
    public access::object_traits< ::PhieuNhapKho >
  {
    public:
    static const std::size_t batch = 1UL;

    struct id_image_type
    {
      char id_value[12];
      ub2 id_size;
      sb2 id_indicator;

      std::size_t version;
    };

    struct image_type
    {
      // mPhieuNhapKhoId
      //
      char mPhieuNhapKhoId_value[12];
      ub2 mPhieuNhapKhoId_size;
      sb2 mPhieuNhapKhoId_indicator;

      // mKhoId
      //
      char mKhoId_value[12];
      ub2 mKhoId_size;
      sb2 mKhoId_indicator;

      // mDanhMucCoQuanTypeId
      //
      char mDanhMucCoQuanTypeId_value[12];
      ub2 mDanhMucCoQuanTypeId_size;
      sb2 mDanhMucCoQuanTypeId_indicator;

      // mSoPhieu
      //
      char mSoPhieu_value[200];
      ub2 mSoPhieu_size;
      sb2 mSoPhieu_indicator;

      // mTenNguoiGiao
      //
      char mTenNguoiGiao_value[200];
      ub2 mTenNguoiGiao_size;
      sb2 mTenNguoiGiao_indicator;

      // mNgayNhapKho
      //
      char mNgayNhapKho_value[7];
      sb2 mNgayNhapKho_indicator;

      // mGhiChu
      //
      char mGhiChu_value[1020];
      ub2 mGhiChu_size;
      sb2 mGhiChu_indicator;

      // mNguoiSuaId
      //
      char mNguoiSuaId_value[12];
      ub2 mNguoiSuaId_size;
      sb2 mNguoiSuaId_indicator;

      // mNgayChinhSua
      //
      char mNgayChinhSua_value[7];
      sb2 mNgayChinhSua_indicator;

      // mTrangThai
      //
      unsigned int mTrangThai_value;
      sb2 mTrangThai_indicator;

      std::size_t version;

      oracle::change_callback change_callback_;

      oracle::change_callback*
      change_callback ()
      {
        return &change_callback_;
      }
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static void
    bind (oracle::bind*,
          image_type&,
          oracle::statement_kind);

    static void
    bind (oracle::bind*, id_image_type&);

    static void
    init (image_type&,
          const object_type&,
          oracle::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef oracle::object_statements<object_type> statements_type;

    typedef oracle::query_base query_base_type;

    static const std::size_t column_count = 10UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::PhieuNhapKho, id_common >:
    public access::object_traits_impl< ::PhieuNhapKho, id_oracle >
  {
  };

  // PhieuNhapKho
  //
}

#include "PhieuNhapKho-odb.ixx"

#include <odb/post.hxx>

#endif // PHIEU_NHAP_KHO_ODB_HXX
